Repository IBM/ibm-grafana-ocpthanos-proxy, pull requests merged in 2023-06, with the labels that each got.

#70 Go version updated to 1.19.10
  Dockerfile
Labels: size/XS

#58 Allow '(...)' and '.*' in namespace regexps
  pkg/proxy/inject.go
Labels: lgtm, size/S, needs-ok-to-test

#71 1.19.10-bullseye flavour updated
  Dockerfile
Labels: lgtm, approved, size/XS
